### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ghost** [KuMarayana/perkenalanGay#1]
Tambahin ini ke forum gay 
![Screenshot_2021-05-31-14-52-54-32](https://user-images.githubusercontent.com/70785472/120317422-cc51ce00-c308-11eb-9d58-2e3b85585442.jpg)

**Comment by KuMarayana** [comment]
Anda gay

Pada tanggal Sel, 1 Jun 2021 19.40, IceCreamUwU ***@***.***>
menulis:
